<?php
/*
* Implementation of hook_ckeditor_plugin
*/
function linkchecker_highlight_ckeditor_ckeditor_plugin() {
	return array(
		'linkchecker_highlight' => array(
			'name' => 'linkchecker_highlight',
			'desc' => t('Underline broken links'),
			// The full path to the CKEditor plugin directory, trailing slash included.
			'path' => drupal_get_path('module', 'linkchecker_highlight_ckeditor') . '/linkchecker_highlight/',
		)
	);
}